#!/bin/bash
################ RNA sequencing analysis ###############

pathhome=/path/to/your/working/directory
pathsw=/path/to/software/

cd $pathhome
mkdir $pathhome/seq 

#then move all the fastq file into "$pathhome/seq" directory

for all_sample in $pathhome/seq/*_1.fastq.gz ; do
  filename=$(basename $all_sample _1.fastq.gz)
  echo $filename

  if [ -d "$pathhome/qc_raw" ] ##read full name before run
   then
     echo "directory exist"
   else 
     echo "creating directory qc_raw"
     mkdir $pathhome/qc_raw
  fi

  echo "Starting quality check of ${filename}"
  $pathsw/FastQC-v0.12.1/fastqc \
  $pathhome/seq/${filename}_1.fastq.gz \
  $pathhome/seq/${filename}_2.fastq.gz \
  -o $pathhome/qc_raw/ \
  -t 40

  if [ -d "$pathhome/trimmed" ] ##read full name before run
   then
     echo "directory exist"
   else 
     echo "creating directory qc_raw"
     mkdir $pathhome/qc_raw
  fi

  echo "Starting trimming ${filename}"
  java -jar /home/ibiolab/Software/Trimmomatic/trimmomatic-0.39.jar PE \
  -threads 40 \
  -phred33 \
  $pathseq/6-9-2023/${filename}_1.fastq.gz \
  $pathseq/6-9-2023/${filename}_2.fastq.gz \
  $path/trim/${filename}_pair_1.fastq.gz \
  $path/trim/${filename}_unpair_1.fastq.gz \
  $path/trim/${filename}_pair_2.fastq.gz \
  $path/trim/${filename}_unpair_2.fastq.gz \
  ILLUMINACLIP:../../ref/TruSeq3-PE.fa:2:30:10:2:keepBothReads \
  LEADING:0 TRAILING:0 SLIDINGWINDOW:4:15 MINLEN:36

  echo "Starting fastqc of trimmed ${filename}"
  /media/ibiolab/Seagate/Software/FastQC-v0.12.1/fastqc \
  $path/trim/${filename}_pair_1.fastq.gz \
  $path/trim/${filename}_pair_2.fastq.gz \
  -o $path/qc_trim/ \
  -t 40

  echo "Starting alignment of ${filename}"
  ../../Software/hisat2-2.2.1/hisat2 \
  -p 40 --dta --add-chrname \
  -x /media/ibiolab/Seagate/ref/Genecode_hisat_index/Genecode_rep \
  -1 $path/trim/${filename}_pair_1.fastq.gz \
  -2 $path/trim/${filename}_pair_2.fastq.gz \
  | /media/ibiolab/Seagate/Software/samtools-1.17/samtools view \
  -@40 \
  -bS \
  -o $path/align/${filename}.bam -

  echo "Starting sorting ${filename}"
  /media/ibiolab/Seagate/Software/samtools-1.17/samtools sort \
  $path/align/${filename}.bam \
  -T $path/sort \
  -o $path/sort/${filename}.sorted.bam

  echo "Starting indexing ${filename}"
  /media/ibiolab/Seagate/Software/samtools-1.17/samtools \
  index \
  $path/sort/${filename}.sorted.bam

  echo "Starting transcript assembly of ${filename}"
  /media/ibiolab/Seagate/Software/stringtie-2.2.1/stringtie \
  -p 40 -G /media/ibiolab/Seagate/ref/gencode.v38.annotation.gtf \
  -o $path/assembly/${filename}.gtf \
  $path/sort/${filename}.sorted.bam

done

echo "Creation of sample_lst.txt"
cd $path/assembly
find $(pwd) -name "*.gtf" > $path/merge/sample_lst.txt
cd ..

echo "Creation of merge.gtf"
/media/ibiolab/Seagate/Software/stringtie-2.2.1/stringtie --merge \
-p 50 -G /media/ibiolab/Seagate/ref/gencode.v38.annotation.gtf \
-o $path/merge/BCa_merge.gtf \
$path/merge/sample_lst.txt

for all_sample in $path/assembly/*.gtf ; do
  filename2=$(basename $all_sample .gtf)
  echo $filename2

  echo "Expression estimation of ${filename2}"
  /media/ibiolab/Seagate/Software/stringtie-2.2.1/stringtie -e -B \
  -p 50 -G $path/merge/BCa_merge.gtf \
  -o $path/expr/${filename2}/${filename2}.gtf \
  $path/sort/${filename2}.sorted.bam
done
